# These are supported funding model platforms

custom: ["https://github.com/sponsors/Furtif", "https://www.patreon.com/ProtoMines", "https://www.paypal.com/donate/?hosted_button_id=WXA874KBC7RNN"]
github: [Furtif]
